kind: Service
apiVersion: v1
metadata:
  name: jellyfin-udp              # < name of the service
  namespace: media-center       # < namespace where to place service
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin-server # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
    metallb.universe.tf/loadBalancerIPs: 192.168.1.212  # < IP to access your jellyfin-server. Should be one from the MetalLB range and the same as the UDP yaml
spec:
  selector:
    app: jellyfin-server           # < reference to the deployment (connects the service with the deployment)
  ports:
  - port: 1900                # < port to open on the outside on the server
    targetPort: 1900          # < targetport. port on the pod to passthrough
    name: dlna-udp            # < reference name for the port in the deployment yaml
    protocol: UDP
  - port: 7359
    targetPort: 7359
    name: discovery-udp
    protocol: UDP
  type: LoadBalancer
---
kind: Service
apiVersion: v1
metadata:
  name: jellyfin-tcp              # < name of the service
  namespace: media-center       # < namespace where to place service
  annotations:
    metallb.universe.tf/allow-shared-ip: jellyfin-server  # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
    metallb.universe.tf/loadBalancerIPs: 192.168.1.212  # < IP to access your jellyfin-server. Should be one from the MetalLB range and the same as the UDP yaml
spec:
  selector:
    app: jellyfin-server           # < reference to the deployment (connects the service with the deployment)
  ports:                      
  - port: 8096               # < port to open on the outside on the server
    targetPort: 8096         # < targetport. port on the pod to passthrough
    name: http-tcp             # < reference name for the port in the deployment yaml
    protocol: TCP
  - port: 8920
    targetPort: 8920
    name: https-tcp
  type: LoadBalancer
