apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: network-system
spec:
  addresses:
  - 192.168.1.204-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k3s-lb
  namespace: network-system
spec:
  ipAddressPools:
    - ip-pool
