apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service-tcp
  namespace: media-center
  annotations:
    metallb.universe.tf/allow-shared-ip: "qbittorrent"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.207
spec:
  selector:
    app: arr-stack
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: dashboard
  - protocol: TCP
    port: 6881
    targetPort: 6881
    name: api
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service-udp
  namespace: media-center
  annotations:
    metallb.universe.tf/allow-shared-ip: "qbittorrent"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.207
spec:
  selector:
    app: arr-stack
  ports:
  - protocol: UDP
    port: 6881
    targetPort: 6881
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  namespace: media-center
spec:
  selector:
    app: arr-stack
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  namespace: media-center
spec:
  selector:
    app: arr-stack
  ports:
  - protocol: TCP
    port: 8989
    targetPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: jackett-service
  namespace: media-center
spec:
  selector:
    app: arr-stack
  ports:
  - protocol: TCP
    port: 9117
    targetPort: 9117
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-dashboard-ingress
  namespace: media-center
spec:
  rules:
  - host: qbittorrent.homelab.maranix.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbittorrent-service-tcp
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-ingress
  namespace: media-center
spec:
  rules:
  - host: radarr.homelab.maranix.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr-service
            port:
              number: 7878
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-ingress
  namespace: media-center
spec:
  rules:
  - host: sonarr.homelab.maranix.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr-service
            port:
              number: 8989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett-ingress
  namespace: media-center
spec:
  rules:
  - host: jackett.homelab.maranix.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jackett-service
            port:
              number: 9117
