# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.208
spec:
  selector:
    app.kubernetes.io/name: portainer
    app.kubernetes.io/instance: portainer
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  type: LoadBalancer
---

