# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: portainer
  namespace: portainer
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.208
spec:
  selector:
    app.kubernetes.io/name: portainer
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: app
    protocol: TCP
    port: 9443
    targetPort: 9443
---

