# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: default
spec:
  selector:
    app.kubernetes.io/name: homepage
  ports:
  - name: app
    protocol: TCP
    port: 80
    targetPort: 3000
---

