## media.persistentvolumeclaim.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media-center"
  name: "pms-config-claim"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media-center"
  name: "media-data"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "1Ti"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media-center"
  name: "media-data1"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "500Gi"
