kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pms-config
  namespace: media-center
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data0
  namespace: media-center
spec:
  storageClassName: ""
  volumeName: nfs-data-storage
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
