version: '3.8'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${CLAIM_TOKEN}
      - ADVERTISE_IP=${SERVER_IP}
    hostname: plex_server
    devices:
      - /dev/dri:/dev/dri #HW Transcoding
    volumes:
      - plex_config:/config
      - ${MOVIE_PATH}:/movies:ro
      - ${TV_PATH}:/tv:ro
    restart: unless-stopped
    
volumes:
  plex_config:
