# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  pihole
  namespace: pihole-system
  labels:
    app:  pihole
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 2
  template:
    metadata:
      labels:
        app:  pihole
    spec:
      containers:
      - name:  pihole
        image:  cbcrowe/pihole-unbound:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: FTLCONF_LOCAL_IPV4
          value: 192.168.1.210
        - name: TZ
          value: Asia/Calcutta
        - name: WEBPASSWORD
          value: pihole
        - name: WEBTHEME
          value: default-dark
        - name: REV_SERVER
          value: "true"
        - name: REV_SERVER_TARGET
          value: 192.168.1.1
        - name: REV_SERVER_CIDR
          value: 192.168.1.0/24
        - name: REV_SERVER_DOMAIN
          value: local
        - name: PIHOLE_DNS_
          value: 127.0.0.1#5335
        - name: DNSSEC
          value: "true"
        - name: DNSMASQ_LISTENING
          value: single
        ports:
        - containerPort:  80
          name:  http
          protocol: TCP
        - containerPort:  53
          name:  comm
          protocol: UDP
        - containerPort:  53
          name:  comm-tcp
          protocol: TCP
        - containerPort:  443
          name:  https
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/pihole
        - name: dnsmasq
          mountPath: /etc/dnsmasq.d
        resources: {}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pihole-config
        - name: dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
      restartPolicy: Always
---
