# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: pihole-lb
  namespace: pihole-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.210
spec:
  selector:
    app: pihole
  type: LoadBalancer
  ports:
  - name: admin
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: comm
    protocol: UDP
    port: 53
    targetPort: 53
  - name: comm-tcp
    protocol: TCP
    port: 53
    targetPort: 53
---

