# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  uptime-kuma
  namespace: uptime-kuma
  labels:
    app:  uptime-kuma
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image:  louislam/uptime-kuma:1.23.11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  3001
          name: http
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /app/data
        resources: {}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: uptime-kuma-config
      restartPolicy: Always
---
