# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.213
spec:
  selector:
    app: uptime-kuma
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
---

