apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.206
spec:
  selector:
    app.kubernetes.io/instance: traefik-kube-system
  type: LoadBalancer
  ports:
    - name: http
      protocol: UDP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: dashboard
      protocol: TCP
      port: 9000
      targetPort: 9000
