apiVersion: v1
kind: Service
metadata:
  name: traefik-service
  namespace: network-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-svc"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.205
spec:
  selector:
    app: traefik
  ports:
    - port: 80
      targetPort: web
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: network-system
  annotations:
    metallb.universe.tf/allow-shared-ip: "traefik-svc"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.205
spec:
  selector:
    app: traefik
  ports:
    - port: 8080
      targetPort: dashboard
  type: LoadBalancer
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-ingress
  namespace: network-system
spec:
  rules:
  - host: traefik.homelab.maranix.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: traefik-dashboard-service
            port:
              number: 8080
