apiVersion: apps/v1
kind: Deployment
metadata:
  name: technitium
  namespace: network-system
  labels:
    app: technitium
spec:
  selector:
    matchLabels:
      app: technitium
  replicas: 1
  template:
    metadata:
      labels:
        app: technitium
    spec:
      nodeSelector:
        kubernetes.io/hostname: wiscos
      hostname: dns-server
      containers:
      - name: technitium
        image: technitium/dns-server:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: Asia/Calcutta
        - name: DNS_SERVER_DOMAIN
          value: dns-server
        - name: DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS
          value: "true"
        - name: DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT
          value: "true"
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 5380
          name: http-console
          protocol: TCP
        - containerPort: 53443
          name: https-console
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/dns
        resources: {}
      securityContext:
        sysctls:
          - name: net.ipv4.ip_local_port_range
            value: 1024 65000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: technitium-config-claim
      restartPolicy: Always
---
