apiVersion: v1
kind: Service
metadata:
  name: technitium-udp
  namespace: network-system
  annotations:
    metallb.universe.tf/allow-shared-ip: technitium # < annotation name to combine the Service IP, make sure it's same name as in the service UDP yaml
    metallb.universe.tf/loadBalancerIPs: 192.168.1.206
spec:
  selector:
    app: technitium
  ports:
  - name: dns-service
    protocol: UDP
    port: 53
    targetPort: 53
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-tcp
  namespace: network-system
  annotations:
    metallb.universe.tf/allow-shared-ip: technitium
    metallb.universe.tf/loadBalancerIPs: 192.168.1.206
spec:
  selector:
    app: technitium
  ports:
  - name: dns-service
    protocol: TCP
    port: 53
    targetPort: 53
  - name: http-console
    protocol: TCP
    port: 5380
    targetPort: 5380
  - name: https-console
    protocol: TCP
    port: 53443
    targetPort: 53443
  externalTrafficPolicy: Local
  type: LoadBalancer
---
