apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pms-config-claim
  namespace: media-center
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
