# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-service
  namespace: longhorn-system
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.206
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ui-ingress
  namespace: longhorn-system
spec:
  rules:
  - host: longhorn.homelab.maranix.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: longhorn-ui-service
            port:
              number: 80
