# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-service
  namespace: longhorn-system
spec:
  selector:
    app: longhorn-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
